name: teste github actions
on: 
  push:
    branches:
      - main
jobs:
  teste-github-actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Criar e ativar venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip pytest

      - name: Rodar testes (usando venv)
        run: |
          venv/bin/python -m pytest treino_githubactions

      - name: Teste finalizado
        run: echo "Teste Finalizado"
